# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Verifica screenshots"
  lane :prerelease do
    Dir.chdir("..") do
        require 'snapshot'

        Snapshot.config = FastlaneCore::Configuration.create(Snapshot::Options.available_options, {})
        Snapshot::ReportsGenerator.new.generate
    end

    frameit(
        silver: true,
        path: './fastlane/screenshots'
    )
  end

  lane :adhoc do
    register_devices(
      devices_file: "./fastlane/devices.txt"
    )

    match(
      git_url: 'https://akamud.visualstudio.com/EventrCertificates/_git/EventrCertificates',
      type: 'adhoc',
      git_user_email: 'mahmoud.ali@outlook.com',
      force_for_new_devices: true
    )
  end
end
