# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone SE",
  "iPhone 6"
])

languages([
   ["pt", "pt_BR"] # Portuguese with Brazilian locale
])

output_directory("./fastlane/screenshots")
project 'Anything.xcodeproj'